[quant][bc-breaking][improvements] Removed quantized_max_pool2d registration
Summary: This PR is part of a series of PRs addressing https://github.com/pytorch/pytorch/issues/54150,
related to using dispatcher for calls to quantized backends as opposed to if/else conditionals.
quantized_max_pool2d has
been removed from the frontend, which was previously not used anyways, after introducing
max_pool2d_with_indices support for quantized tensors.

BC-breaking note:
Previous:
```
import torch
x = torch.rand(1, 1, 1, 1)
qx = torch.quantize_per_tensor(x, scale=0.5, zero_point=0, dtype=torch.qint8)
max_pooled_qx = torch.quantized_max_pool2d(qx, kernel_size=1)
print(qx)
print(max_pooled_qx)
```

Result:
```
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
```

After:
```
import torch
x = torch.rand(1, 1, 1, 1)
qx = torch.quantize_per_tensor(x, scale=0.5, zero_point=0, dtype=torch.qint8)
max_pooled_qx = torch.quantized_max_pool2d(qx, kernel_size=1)
print(qx)
print(max_pooled_qx)
```

Result
```
AttributeError: module 'torch' has no attribute 'quantized_max_pool2d'
```

Now we must use:
```
import torch
x = torch.rand(1, 1, 1, 1)
qx = torch.quantize_per_tensor(x, scale=0.5, zero_point=0, dtype=torch.qint8)
max_pooled_qx = torch.max_pool2d(qx, kernel_size=1)
print(qx)
print(max_pooled_qx)
```

Result
```
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
tensor([[[[1.]]]], size=(1, 1, 1, 1), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=0)
```

Test plan:
```
python test/test_quantization.py -k test_max_pool2d
```

ghstack-source-id: 17ef495e0b026c6ef657ec32f399d5af6643ed45
Pull Request resolved: https://github.com/pytorch/pytorch/pull/75304